== Usage

To use this plugin, execute the `ngGenerateAll` command and pass the fully qualified path of a domain class

[source,sh,indent="1"]
----
$ grails ngGenerateAll com.foo.Bar
----

The command will generate everything required to create, read, update, and delete instances of domain classes with AngularJS. The following will be created if they don't already exist.

. A module for the domain `/grails-app/assets/javascripts/com/foo/com.foo.bar.js`.
. Templates for create, edit, list, and show `/grails-app/assets/javascripts/com/foo/templates/create.tpl.html`.
.. A form template will also be created that is used by both create and edit.
. Controllers for create, edit, list, and show `/grails-app/assets/javascripts/com/foo/controllers/BarCreateController.js`.
. A javascript representation of the domain class `/grails-app/assets/javascripts/com/foo/domain/Bar.js`.

Based on the properties of your domain, some other assets may be generated.

=== File Properties

If your domain contains a `byte[]`, `Byte[]`, or `java.sql.Blob` then a few things will change.

. The javascript representation of the domain class will be modified to send a `FormData` instead of a standard JSON request body.
. A directive will be created to store the representation of the file instead of `ng-model`, which doesn't support inputs of type file.

=== Associations

If your domain has associations to other domain classes, that will influence the scaffolding.

. Services will be created to convert plain objects in response data to instances of their respective javascript domains
. The javascript domain class will be updated to use the services created
. Modules and JavaScript domain classes will be created for all associated entities. The assets created by this process are designed to be used solely by the associated domain, not by a separate CRUD interface.

IMPORTANT: When generating assets for a domain class that already has a module and a JavaScript domain class created via an association, ensure you inform the command to overwrite.
[source,sh,indent="1"]
----
$ grails ngGenerateAll com.foo.Bar true
----

=== Supporting module

If a module with the name "core" exists in the same directory that your module's directory is in, the core module will be considered the "supporting module". Otherwise, the module for the domain being rendered will be considered the supporting module.

The directive to assist with file uploads, as well as the services to assist with domain conversions will be stored in what is calculated to be the supporting module. In addition, the core module will be defined as a dependency in the module being generated.

Example:
[source,sh,indent="1"]
----
$ grails ngGenerateAll com.foo.Bar
----

The scaffolding will look for `/grails-app/assets/javascripts/com/foo/core/com.foo.core.js`. If it is found, it will be the supporting module.

=== Assumptions

This plugin needs certain third party libraries to function and it assumes they are available. In addition to angular itself, the plugin relies on link:https://github.com/angular-ui/ui-router[ui-router] for routing.

If you are using this plugin without the angular profile in Grails 3.2.0 or greater, it will be up to you to ensure those assets are available in the project. You can inform the plugin of their location with configuration.

=== Routing

If you are using the angular profile in Grails 3.2.0 or higher, the default index page is modified so that clicking on the link to the controller will automatically route you to the module the controller represents. If you are using this plugin in an existing application, you will have a little bit of work to do to use the generated assets.

The first step is to ensure the module is included in the page. If a parent module is found, a dependency will automatically be created, however it is up to you to ensure the parent module or the generated module is included on the page using asset pipeline as you normally would.

Example:
[source,sh,indent="1"]
----
$ grails ngGenerateAll com.foo.Bar
----

If `/grails-app/assets/javascripts/com/foo/com.foo.js` exists, a dependency will be created in `com.foo.js` to require `/com/foo/bar/com.foo.bar.js`.

The following states are defined in generated modules:

. `/domain`
. `/domain/create`
. `/domain/edit/:id`
. `/domain/show/:id`

Assuming the script has been loaded on the index page and there is a `ui-view` directive on the index page, the URL would be `http://localhost:8080/#domain`. See the documentation for link:https://github.com/angular-ui/ui-router/wiki[UI-Router] for more information.

